version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: ./server
    ports:
      - '4000:4000'
    depends_on:
      - mongo

  frontend:
    build: .
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - server
